chore(android): 🚧 building android project architecture

diff --git a/example/android/gradlew b/example/android/gradlew
--- a/example/android/gradlew
+++ b/example/android/gradlew
@@ -70,13 +70,13 @@ app_path=$0
 # Need this for daisy-chained symlinks.
 while
     APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
-    [ -h "$app_path" ]
+    [ -h "${app_path}" ]
 do
-    ls=$( ls -ld "$app_path" )
+    ls=$( ls -ld "${app_path}" )
     link=${ls#*' -> '}
-    case $link in             #(
-      /*)   app_path=$link ;; #(
-      *)    app_path=$APP_HOME$link ;;
+    case ${link} in             #(
+      /*)   app_path=${link} ;; #(
+      *)    app_path=${APP_HOME}${link} ;;
     esac
 done
 
@@ -114,19 +114,19 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
+CLASSPATH=${APP_HOME}/gradle/wrapper/gradle-wrapper.jar
 
 
 # Determine the Java command to use to start the JVM.
-if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+if [ -n "${JAVA_HOME}" ] ; then
+    if [ -x "${JAVA_HOME}/jre/sh/java" ] ; then
         # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD=$JAVA_HOME/jre/sh/java
+        JAVACMD=${JAVA_HOME}/jre/sh/java
     else
-        JAVACMD=$JAVA_HOME/bin/java
+        JAVACMD=${JAVA_HOME}/bin/java
     fi
-    if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+    if [ ! -x "${JAVACMD}" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: ${JAVA_HOME}
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
@@ -140,17 +140,17 @@ location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
-if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
-    case $MAX_FD in #(
+if ! "${cygwin}" && ! "${darwin}" && ! "${nonstop}" ; then
+    case ${MAX_FD} in #(
       max*)
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
-    case $MAX_FD in  #(
+    case ${MAX_FD} in  #(
       '' | soft) :;; #(
       *)
-        ulimit -n "$MAX_FD" ||
-            warn "Could not set maximum file descriptor limit to $MAX_FD"
+        ulimit -n "${MAX_FD}" ||
+            warn "Could not set maximum file descriptor limit to ${MAX_FD}"
     esac
 fi
 
@@ -163,23 +163,23 @@ fi
 #   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
 
 # For Cygwin or MSYS, switch paths to Windows format before running java
-if "$cygwin" || "$msys" ; then
-    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
-    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
+if "${cygwin}" || "${msys}" ; then
+    APP_HOME=$( cygpath --path --mixed "${APP_HOME}" )
+    CLASSPATH=$( cygpath --path --mixed "${CLASSPATH}" )
 
-    JAVACMD=$( cygpath --unix "$JAVACMD" )
+    JAVACMD=$( cygpath --unix "${JAVACMD}" )
 
     # Now convert the arguments - kludge to limit ourselves to /bin/sh
     for arg do
         if
-            case $arg in                                #(
+            case ${arg} in                                #(
               -*)   false ;;                            # don't mess with options #(
               /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
-                    [ -e "$t" ] ;;                      #(
+                    [ -e "${t}" ] ;;                      #(
               *)    false ;;
             esac
         then
-            arg=$( cygpath --path --ignore --mixed "$arg" )
+            arg=$( cygpath --path --ignore --mixed "${arg}" )
         fi
         # Roll the args list around exactly as many times as the number of
         # args, so each arg winds up back in the position where it started, but
@@ -189,7 +189,7 @@ if "$cygwin" || "$msys" ; then
         # changing the positional parameters here affects neither the number of
         # iterations, nor the values presented in `arg`.
         shift                   # remove old arg
-        set -- "$@" "$arg"      # push replacement arg
+        set -- "$@" "${arg}"      # push replacement arg
     done
 fi
 
@@ -200,8 +200,8 @@ fi
 #   * put everything else in single quotes, so that it's not re-expanded.
 
 set -- \
-        "-Dorg.gradle.appname=$APP_BASE_NAME" \
-        -classpath "$CLASSPATH" \
+        "-Dorg.gradle.appname=${APP_BASE_NAME}" \
+        -classpath "${CLASSPATH}" \
         org.gradle.wrapper.GradleWrapperMain \
         "$@"
 
@@ -225,10 +225,10 @@ set -- \
 #
 
 eval "set -- $(
-        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
+        printf '%s\n' "${DEFAULT_JVM_OPTS} ${JAVA_OPTS} ${GRADLE_OPTS}" |
         xargs -n1 |
         sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
         tr '\n' ' '
     )" '"$@"'
 
-exec "$JAVACMD" "$@"
+exec "${JAVACMD}" "$@"
